// Generated by gencpp from file integration_test/testmsg.msg
// DO NOT EDIT!


#ifndef INTEGRATION_TEST_MESSAGE_TESTMSG_H
#define INTEGRATION_TEST_MESSAGE_TESTMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace integration_test
{
template <class ContainerAllocator>
struct testmsg_
{
  typedef testmsg_<ContainerAllocator> Type;

  testmsg_()
    : sequenceNum(0)  {
    }
  testmsg_(const ContainerAllocator& _alloc)
    : sequenceNum(0)  {
  (void)_alloc;
    }



   typedef uint8_t _sequenceNum_type;
  _sequenceNum_type sequenceNum;





  typedef boost::shared_ptr< ::integration_test::testmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::integration_test::testmsg_<ContainerAllocator> const> ConstPtr;

}; // struct testmsg_

typedef ::integration_test::testmsg_<std::allocator<void> > testmsg;

typedef boost::shared_ptr< ::integration_test::testmsg > testmsgPtr;
typedef boost::shared_ptr< ::integration_test::testmsg const> testmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::integration_test::testmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::integration_test::testmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::integration_test::testmsg_<ContainerAllocator1> & lhs, const ::integration_test::testmsg_<ContainerAllocator2> & rhs)
{
  return lhs.sequenceNum == rhs.sequenceNum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::integration_test::testmsg_<ContainerAllocator1> & lhs, const ::integration_test::testmsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace integration_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::integration_test::testmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::integration_test::testmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::integration_test::testmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::integration_test::testmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::integration_test::testmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::integration_test::testmsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::integration_test::testmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96f4abd1a5050e1e1afc651209403d91";
  }

  static const char* value(const ::integration_test::testmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96f4abd1a5050e1eULL;
  static const uint64_t static_value2 = 0x1afc651209403d91ULL;
};

template<class ContainerAllocator>
struct DataType< ::integration_test::testmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "integration_test/testmsg";
  }

  static const char* value(const ::integration_test::testmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::integration_test::testmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 sequenceNum\n"
;
  }

  static const char* value(const ::integration_test::testmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::integration_test::testmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequenceNum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::integration_test::testmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::integration_test::testmsg_<ContainerAllocator>& v)
  {
    s << indent << "sequenceNum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sequenceNum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTEGRATION_TEST_MESSAGE_TESTMSG_H
